#!/usr/bin/env python

import pprint

def createTestCollection():
    testCollection =[
        {u'dataProvider':'a',
         u'id':'1-DPLA Fails- fields absent',
         u'isShownAt':'a',
         u'object':'a' ,
         u'originalRecord': {1:'annoying nested dict'},
         u'provider': {1:2, 2:3, 3:4},
         u'sourceResource': {u'collection':{u'@id': u'http://dp.lapi/collect',
                                            u'description': u'about a bike',
                                            u'id': u'3cbf478cc2d9d448daa7ca42',
                                            u'title': u'The Daily Collecton'},
                             u'creator': [u'Daily Reflect (Greenville, N.C.)'],
                             u'date': {u'begin': u'1963-10-27',
                                       u'displayDate': u'19631027',
                                       u'end': u'1963-10-27'},
                             u'description': [u'children standing a bicycle.'],
                             u'format': u'negatives (photographic)',
                             u'publisher': u'https://digital.lib.ecu.edu/6570',
                             u'language': [{u'iso639_3': u'eng',
                                            u'name': u'English'}],
                             u'rights': u'Copyright held by Joyner Library.',
                             u'spatial': [{u'name': u'United States--North'}],
                             u'stateLocatedIn': [{u'name': u'North Carolina'}],
                             u'subject': [{u'name': u'Children--Greenville'},
                                          {u'name': u'Bicycles--Greenville'},
                                          {u'name': u'Economics'}],
                             u'title': [u'Bicycle'],
                             u'type': u'image'}}
,
        {u'aggregatedCHO':'!@#$%^&*(',
         u'dataProvider':'the Feds',
         u'id': '2- DPLA Fails - fields not alphanumeric',
         u'isShownAt':'Mars',
         u'object':'a' ,
         u'originalRecord':{u'collection': {u'@id': u'http://dp.la/api/colle',
                                            u'description': u'',
                                            u'id': u'3cbf478cc48daa7a42c3b0f2',
                                            u'title': u'The Daillector Image'},
                            u'header': {u'datestamp': u'2014-09-18',
                                        u'setSpec': u'ecu_c5'},
                            u'id': u'urn:brevard.lib.unc.eduececu.edu/6570',
                            u'provider': {u'@id': u'http://dp.la/api/digitc',
                                          u'name': u'North CarolinHeritater'}},
         u'provider': {'a':[1, 2, 84, 99, 100]},
         u'sourceResource': {u'collection': {u'@id': u'http://dp.la/i/collect',
                                             u'description': u'about a bike',
                                             u'id': u'3cbf478d9d448daa7c73a42',
                                             u'title': u'The Daily llection'},
                             u'creator': [u'Daily Reflector (Greenville,C.)'],
                             u'date': {u'begin': u'1963-10-27',
                                       u'displayDate': u'19631027',
                                       u'end': u'1963-10-27'},
                             u'description': [u'children standind a bicycle.'],
                             u'format': u'negatives (photographic)',
                             u'publisher': u'https://digital.lib.ecu.edu/6570',
                             u'language': [{u'iso639_3': u'eng',
                                            u'name': u'English'}],
                             u'rights': u'Copyright held by Joyner Library.',
                             u'spatial': [{u'name': u'United States--North'}],
                             u'stateLocatedIn': [{u'name': u'North Carolina'}],
                             u'subject': [{u'name': u'Children--Greenville'},
                                          {u'name': u'Bicycles--Greenville'},
                                          {u'name': u'Economics'}],
                             u'title': [u'Bicycle'],
                             u'type': u'image'}}
,
        {u'aggregatedCHO':'some aggregated thing',
         u'dataProvider':'yo mamma',
         u'id':'3-Every thing 100% good',
         u'isShownAt':'the movies',
         u'object': 'fork',
         u'originalRecord':{u'collection': {u'@id': u'http://dp.la/api/colle',
                                            u'description': u'',
                                            u'id': u'3ccc2d9d448daa7a42c3b0f2',
                                            u'title': u'Tily Reflector Image'},
                            u'header': {u'datestamp': u'2014-09-18',
                                        u'setSpec': u'ecu_c5'},
                            u'id': u'urn:brevard.lib.unc.eduecuecu.edu/6570',
                            u'provider': {u'@id': u'http://dp.la/aigitalnc',
                                          u'name': u'North CarolinHe Center'}},
         u'provider': {1:'foo', 2:'bar', 3:'silly walk'},
         u'sourceResource': {u'collection': {u'@id': u'http://dp.la/apollect',
                                             u'description': u'about a bike',
                                             u'id': u'3cbf478cc2d9d447c73a42',
                                             u'title': u'The Daily Collect'},
                             u'creator': [u'Daily Reflector (Greenville,.)'],
                             u'date': {u'begin': u'1963-10-27',
                                       u'displayDate': u'19631027',
                                       u'end': u'1963-10-27'},
                             u'description': [u'children standind a bicycle.'],
                             u'format': u'negatives (photographic)',
                             u'publisher': u'https://digital.lib.ecu.edu/6570',
                             u'language': [{u'iso639_3': u'eng',
                                            u'name': u'English'}],
                             u'rights': u'Copyright held by Joyner Library.',
                             u'spatial': [{u'name': u'United States--North'}],
                             u'stateLocatedIn': [{u'name': u'North Carolina'}],
                             u'subject': [{u'name': u'Children--Greenville'},
                                          {u'name': u'Bicycles--Greenville'},
                                          {u'name': u'Economics'}],
                             u'title': [u'Bicycle'],
                             u'type': u'image'}}
        ,
        {u'aggregatdCHO':'dfghj',
         u'datovider':'ghj',
         u'id':'4- All fields missing',
         u'ishownAt':'',
         u'oject': '',
         u'orginalRecord': {u'collecion': {u'@id': u'http://dp.la/api/colle',
                                           u'dcription': u'',
                                           u'id': u'3cbf2d9d448daa7a42c3b0f2',
                                           u'titlte': u'The Daily tor Image'},
                            u'header': {u'datestamp': u'2014-09-18',
                                        u'setSpec': u'ecu_c5'},
                            u'id': u'urn:brevard.lib.unc.eduecu.edu/6570',
                            u'provider': {u'@id': u'http://dp.lai/digitalnc',
                                          u'name': u'North Caroliage Center'}},
         u'proder': {'':''},
         u'srceResource':{u'colection': {u'@id': u'http://dp.la/apollect',
                                         u'decription': u'about a bike',
                                         u'id': u'3cbf478cc2d9d448daa7c73a42',
                                         u'ttle': u'The Daily Collection'},
                          u'creaor': [u'Daily Reflector (Greenville, N.C.)'],
                          u'dae': {u'begin': u'1963-10-27',
                                   u'diplayDate': u'19631027',
                                   u'end': u'1963-10-27'},
                          u'decription': [u'children standiehind a bicycle.'],
                          u'fomat': u'negatives (photographic)',
                          u'pulisher': u'https://digital.lib.ecu.edu/6570',
                          u'laguage': [{u'iso639_3': u'eng',
                                        u'name': u'English'}],
                          u'rghts': u'Copyright held by Joyner Library.',
                          u'satial': [{u'name': u'United States--North'}],
                          u'sateLocatedIn': [{u'name': u'North Carolina'}],
                          u'sbject': [{u'name': u'Children--Greenville'},
                                      {u'name': u'Bicycles--Greenville'},
                                      {u'name': u'Economics'}],
                          u'title': [u'Bicycle'],
                          u'tye': u'image'}}
        ,
        {u'aggregatedCHO':'dfghj',
         u'dataProvider':'',
         u'id':'5-All fields present but empty',
         u'isShownAt':'',
         u'object':'' ,
         u'originalRecord':'sdfgh',
         u'provider': '',
         u'sourceResource': {u'collection':'',
                             u'creator': '',
                             u'date': {u'displayDate': u''},
                             u'description': '',
                             u'format':u'',
                             u'publisher': u'',
                             u'language': '',
                             u'rights': u'right',
                             u'spatial': '',
                             u'stateLocatedIn':'',
                             u'subject':'',
                             u'title': [u'Bicycle'],
                             u'type': ''}}
        ,
        {u'aggregatedCHO':'skjfg',
         u'dataProvider':'@#$%^&*',
         u'id':'6-All fields present and non-alphanumeric',
         u'isShownAt':'#$%^&*()',
         u'object': '!@#$%^&*',
         u'originalRecord': {'a':'1',
                             u'header': {u'datestamp': u'2014-09-18',
                                         u'setSpec': u'ecu_c5'},
                             u'id': u'urnd.lib.unc.eduecu_c5:oa.ecu.edu/6570',
                             u'provider': {u'@id': u'http://d/api/digitalnc',
                                           u'name': u'North Carolin Center'}},
         u'provider': {'#':'$'},
         u'sourceResource': {u'collection': {u'@id': u'http://dp.la/api/clct',
                                             u'description': u'#$%^&',
                                             'id': u'3cbfc2d448daa7c73a42',
                                             u'title': u'#$%^&*('},
                             u'creator': [u'%^&*'],
                             u'date': {u'begin': u'$%^&*',
                                       u'displayDate': u'$%^&*',
                                       u'end': u'%^&*'},
                             u'description': [u'#'],
                             u'format': u'@',
                             u'publisher': u'*()_',
                             u'language': [{u'@': u'%^&*',
                                            u'!': u'$%^&'}],
                             u'rights': u'Copyright held by Joyner Library.',
                             u'spatial': [{u'#$%^': u'#$%^&*'}],
                             u'stateLocatedIn': [{u'#$%^&': u'$%^&*('}],
                             u'subject': [{u'#$%^&*': u'+++++'},
                                          {u'@#$%^': u'$%^&'},
                                          {u'#$%^': u'%^&*('}],
                             u'title': [u'Bicycle'],
                             u'type': u'^&*('}}
        ,
        {u'aggregatedCHO':[1,2,3],
         u'dataProvider':'fghj',
         u'id':'7-all fields present exept for title',
         u'isShownAt':'dfghjk',
         u'object': 'rtyuio',
         u'originalRecord': {'nested dict':'lfkgb'},
         u'provider': {'ghj':'@', '1':'', '4':'ghjk'},
         u'sourceResource': {u'collection': {u'@id': u'http://dp.la/api/clect',
                                             u'description': u'about a bike',
                                             u'id': u'3cbf47d9d448daa7c73a42',
                                             u'title': u'The Daiollection'},
                             u'creator': [u'Daily Reflector (Greenvil, N.C.)'],
                             u'date': {u'begin': u'1963-10-27',
                                       u'displayDate': u'19631027',
                                       u'end': u'1963-10-27'},
                             u'description': [u'children stanhind a bicycle.'],
                             u'format': u'negatives (photographic)',
                             u'publisher': u'https://digital.lib.ecu.edu/6570',
                             u'language': [{u'iso639_3': u'eng',
                                            u'name': u'English'}],
                             u'rights': u'Copyright held by Joyner Library.',
                             u'spatial': [{u'name': u'United States--North'}],
                             u'stateLocatedIn': [{u'name': u'North Carolina'}],
                             u'subject': [{u'name': u'Children--Greenville'},
                                          {u'name': u'Bicycles--Greenville'},
                                          {u'name': u'Economics'}],
                             u'type': u'image'}}
        ,
        {u'aggregatedCHO':'fghjk',
         u'dataProvider':'dfghjkl',
         u'id':'8-all fields present rights empty',
         u'isShownAt':'fghjk',
         u'object': 'dfghj',
         u'originalRecord': {u'collection': {u'@id': u'http://dp.la/api/colle',
                                             u'description': u'',
                                             u'id': u'3cbf478cc2d9d442c3b0f2',
                                             u'title': u'The Daily ReflImage'},
                             u'header': {u'datestamp': u'2014-09-18',
                                         u'setSpec': u'ecu_c5'},
                             u'id': u'urn:brevard.lib.unc.eduecu_cdu/6570',
                             u'provider': {u'@id': u'http://dp.api/digitalnc',
                                           u'name': u'North Carotage Center'}},
         u'provider': {1:3},
         u'sourceResource': {u'collection': {u'@id': u'http://dp.la/api/clect',
                                             u'description': u'about a bike',
                                             u'id': u'3cbf4789d448daa7c73a42',
                                             u'title': u'The Daily Collect'},
                             u'creator': [u'Daily Reflect (Greenville, N.C.)'],
                             u'date': {u'begin': u'1963-10-27',
                                       u'displayDate': u'19631027',
                                       u'end': u'1963-10-27'},
                             u'description': [u'children standind a bicycle.'],
                             u'format': u'negatives (photographic)',
                             u'publisher': u'https://digital.lib.ecu.edu/6570',
                             u'language': [{u'iso639_3': u'eng',
                                            u'name': u'English'}],
                             u'rights': u'',
                             u'spatial': [{u'name': u'United States--North'}],
                             u'stateLocatedIn': [{u'name': u'North Carolina'}],
                             u'subject': [{u'name': u'Children--Greenville'},
                                          {u'name': u'Bicycles--Greenville'},
                                          {u'name': u'Economics'}],
                             u'title': [u'Bicycle'],
                             u'type': u'image'}}
        ,
        {u'aggregatedCHO':'dfghj',
         u'dataProvider':'dfghjk',
         u'id':'9- all fields present title is non-alphanumeric',
         u'isShownAt':'dfghj',
         u'object':'dfghjk' ,
         u'originalRecord': {u'collection': {u'@id': u'http://dp.la/api/colle',
                                             u'description': u'',
                                             u'id': u'3cbf478c8daa7a42c3b0f2',
                                             u'title': u'The Dalector Image'},
                             u'header': {u'datestamp': u'2014-09-18',
                                         u'setSpec': u'ecu_c5'},
                             u'id': u'urn:brevard.lib.unc.eduecu_cu.edu/6570',
                             u'provider': {u'@id': u'http://dp.la/apiitalnc',
                                           u'name': u'North CarolinHeenter'}},
         u'provider': {3:'bark'},
         u'sourceResource': {u'collection': {u'@id': u'http://dp.la/api/clect',
                                             u'description': u'about a bike',
                                             u'id': u'3cbf478d448daa7c73a42',
                                             u'title': u'The Dailllection'},
                             u'creator': [u'Daily Reflector (GreenvN.C.)'],
                             u'date': {u'begin': u'1963-10-27',
                                       u'displayDate': u'19631027',
                                       u'end': u'1963-10-27'},
                             u'description': [u'children standnd a bicycle.'],
                             u'format': u'negatives (photographic)',
                             u'publisher': u'https://digital.lib.ecu.edu/6570',
                             u'language': [{u'iso639_3': u'eng',
                                            u'name': u'English'}],
                             u'rights': u'Copyright held by Joyner Library.',
                             u'spatial': [{u'name': u'United States--North'}],
                             u'stateLocatedIn': [{u'name': u'North Carolina'}],
                             u'subject': [{u'name': u'Children--Greenville'},
                                          {u'name': u'Bicycles--Greenville'},
                                          {u'name': u'Economics'}],
                             u'title': [u'^&*'],
                             u'type': u'image'}}
        ,
        {u'aggregatedCHO':'dfghjk',
         u'dataProvider':'ryuio',
         u'id':'10-sr.date.displayDate has status 5, sr.spatial has status 6',
         u'isShownAt':'dfghjk',
         u'object': 'er',
         u'originalRecord': {u'collection': {u'@id': u'http://dp.la/api/colle',
                                             u'description': u'',
                                             u'id': u'3cb2d9d448daa7a42c3b0f2',
                                             u'title': u'Thy Reflector Image'},
                             u'header': {u'datestamp': u'2014-09-18',
                                         u'setSpec': u'ecu_c5'},
                             u'id': u'urn:brevard.lib.unc.edueccu.edu/6570',
                             u'provider': {u'@id': u'http://dp.la/aigitalnc',
                                           u'name': u'North Carolin Center'}},
         u'provider': {'sdfghj'},
         u'sourceResource': {u'collection': {u'@id': u'http://dp.la/api/collt',
                                             u'description': u'about a bike',
                                             u'id': u'3cbf478c448daa7c73a42',
                                             u'title': u'The Daily lection'},
                             u'creator': [u'Daily Reflector (GreenvilleC.)'],
                             u'description': [u'children standing behiycle.'],
                             u'format': u'negatives (photographic)',
                             u'publisher': u'https://digital.lib.ecu.edu/6570',
                             u'language': [{u'iso639_3': u'eng',
                                            u'name': u'English'}],
                             u'rights': u'Copyright held by Joyner Library.',
                             u'spatial': [{u'narme': u''}],
                             u'stateLocatedIn': [{u'name': u'North Carolina'}],
                             u'subject': [{u'name': u'Children--Greenville'},
                                          {u'name': u'Bicycles--Greenville'},
                                          {u'name': u'Economics'}],
                             u'title': [u'Bicycle'],
                             u'type': u'image'}}
        ,
        {u'aggregatedCHO':'fghjk',
         u'dataProvider':'fghjk',
         u'id':'11- sr.date has status 7, sr.spatial as status 8',
         u'isShownAt':'fghjk',
         u'object':'fghjk' ,
         u'originalRecord': {u'collection': {u'@id': u'http://dp.la/api/colle',
                                             u'description': u'',
                                             u'id': u'3cbf4d448daa7a42c3b0f2',
                                             u'title': u'The Reflector Image'},
                             u'header': {u'datestamp': u'2014-09-18',
                                         u'setSpec': u'ecu_c5'},
                             u'id': u'urn:brevard.lib.unc.eduecucu.edu/6570',
                             u'provider': {u'@id': u'http://dp.la/apigitalnc',
                                           u'name': u'North CarolinHeenter'}},
         u'provider': {'d':'d'},
         u'sourceResource': {u'collection': {u'@id': u'http://dp.la/api/clect',
                                             u'description': u'about a bike',
                                             u'id': u'3cbf478cc48daa7c73a42',
                                             u'title': u'The Daily ection'},
                             u'creator': [u'Daily Reflector (GreenvilleC.)'],
                             u'date': {u'begin': u'1963-10-27',
                                       u'displayDate': u'',
                                       u'end': u'1963-10-27'},
                             u'description': [u'children standind a bicycle.'],
                             u'format': u'negatives (photographic)',
                             u'publisher': u'https://digital.lib.ecu.edu/6570',
                             u'language': [{u'iso639_3': u'eng',
                                            u'name': u'English'}],
                             u'rights': u'Copyright held by Joyner Library.',
                             u'spatial': [{u'name': u'%^&*'}],
                             u'stateLocatedIn': [{u'name': u'North Carolina'}],
                             u'subject': [{u'name': u'Children--Greenville'},
                                          {u'name': u'Bicycles--Greenville'},
                                          {u'name': u'Economics'}],
                             u'title': [u'Bicycle'],
                             u'type': u'image'}}
    ]

    return testCollection
    

testCollection = createTestCollection()
pprint.pprint(testCollection)

for item in testCollection:
    print item['id']

